# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/fieldui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(342, 357)
        Dialog.setModal(True)
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 21, 301, 271))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.name = QtGui.QLineEdit(self.formLayoutWidget)
        self.name.setObjectName(_fromUtf8("name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.name)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.length = QtGui.QLineEdit(self.formLayoutWidget)
        self.length.setObjectName(_fromUtf8("length"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.length)
        self.default_2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.default_2.setObjectName(_fromUtf8("default_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.default_2)
        self.type = QtGui.QComboBox(self.formLayoutWidget)
        self.type.setObjectName(_fromUtf8("type"))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.type.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.type)
        self.uns = QtGui.QCheckBox(self.formLayoutWidget)
        self.uns.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uns.setText(_fromUtf8(""))
        self.uns.setChecked(False)
        self.uns.setTristate(False)
        self.uns.setObjectName(_fromUtf8("uns"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.uns)
        self.nullable = QtGui.QCheckBox(self.formLayoutWidget)
        self.nullable.setText(_fromUtf8(""))
        self.nullable.setObjectName(_fromUtf8("nullable"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nullable)
        self.autoincrement = QtGui.QCheckBox(self.formLayoutWidget)
        self.autoincrement.setText(_fromUtf8(""))
        self.autoincrement.setObjectName(_fromUtf8("autoincrement"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.autoincrement)
        self.key = QtGui.QComboBox(self.formLayoutWidget)
        self.key.setObjectName(_fromUtf8("key"))
        self.key.addItem(_fromUtf8(""))
        self.key.setItemText(0, _fromUtf8(""))
        self.key.addItem(_fromUtf8(""))
        self.key.addItem(_fromUtf8(""))
        self.key.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.key)
        self.saveBtn = QtGui.QPushButton(Dialog)
        self.saveBtn.setGeometry(QtCore.QRect(220, 310, 101, 31))
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.name, self.type)
        Dialog.setTabOrder(self.type, self.length)
        Dialog.setTabOrder(self.length, self.uns)
        Dialog.setTabOrder(self.uns, self.nullable)
        Dialog.setTabOrder(self.nullable, self.key)
        Dialog.setTabOrder(self.key, self.default_2)
        Dialog.setTabOrder(self.default_2, self.autoincrement)
        Dialog.setTabOrder(self.autoincrement, self.saveBtn)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Field:", None))
        self.label_2.setText(_translate("Dialog", "Type:", None))
        self.label_3.setText(_translate("Dialog", "Length:", None))
        self.label_4.setText(_translate("Dialog", "Unsigned:", None))
        self.label_5.setText(_translate("Dialog", "Nullable:", None))
        self.label_6.setText(_translate("Dialog", "Key:", None))
        self.label_7.setText(_translate("Dialog", "Default:", None))
        self.label_8.setText(_translate("Dialog", "AutoIncrement:", None))
        self.type.setItemText(0, _translate("Dialog", "int", None))
        self.type.setItemText(1, _translate("Dialog", "tinyint", None))
        self.type.setItemText(2, _translate("Dialog", "smallint", None))
        self.type.setItemText(3, _translate("Dialog", "mediumint", None))
        self.type.setItemText(4, _translate("Dialog", "char", None))
        self.type.setItemText(5, _translate("Dialog", "varchar", None))
        self.type.setItemText(6, _translate("Dialog", "bigint", None))
        self.type.setItemText(7, _translate("Dialog", "float", None))
        self.type.setItemText(8, _translate("Dialog", "double", None))
        self.type.setItemText(9, _translate("Dialog", "decimal", None))
        self.type.setItemText(10, _translate("Dialog", "date", None))
        self.type.setItemText(11, _translate("Dialog", "datetime", None))
        self.type.setItemText(12, _translate("Dialog", "timestamp", None))
        self.type.setItemText(13, _translate("Dialog", "time", None))
        self.type.setItemText(14, _translate("Dialog", "year", None))
        self.type.setItemText(15, _translate("Dialog", "text", None))
        self.type.setItemText(16, _translate("Dialog", "tinytext", None))
        self.type.setItemText(17, _translate("Dialog", "mediumtext", None))
        self.type.setItemText(18, _translate("Dialog", "longtext", None))
        self.type.setItemText(19, _translate("Dialog", "enum", None))
        self.key.setItemText(1, _translate("Dialog", "primary", None))
        self.key.setItemText(2, _translate("Dialog", "unique", None))
        self.key.setItemText(3, _translate("Dialog", "multiple", None))
        self.saveBtn.setText(_translate("Dialog", "Save", None))

