# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/mainui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(773, 592)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setMargin(9)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalWidget = QtGui.QWidget(self.splitter)
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_5.setContentsMargins(1, 15, 1, 1)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.databases = QtGui.QComboBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databases.sizePolicy().hasHeightForWidth())
        self.databases.setSizePolicy(sizePolicy)
        self.databases.setBaseSize(QtCore.QSize(0, 0))
        self.databases.setStyleSheet(_fromUtf8(""))
        self.databases.setEditable(False)
        self.databases.setObjectName(_fromUtf8("databases"))
        self.databases.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.databases)
        self.sidebar = QtGui.QStackedWidget(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar.setBaseSize(QtCore.QSize(0, 0))
        self.sidebar.setFrameShape(QtGui.QFrame.NoFrame)
        self.sidebar.setFrameShadow(QtGui.QFrame.Plain)
        self.sidebar.setLineWidth(1)
        self.sidebar.setObjectName(_fromUtf8("sidebar"))
        self.sidebarPage1 = QtGui.QWidget()
        self.sidebarPage1.setObjectName(_fromUtf8("sidebarPage1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.sidebarPage1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.favorites = QtGui.QListWidget(self.sidebarPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favorites.sizePolicy().hasHeightForWidth())
        self.favorites.setSizePolicy(sizePolicy)
        self.favorites.setMinimumSize(QtCore.QSize(10, 0))
        self.favorites.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.favorites.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.favorites.setObjectName(_fromUtf8("favorites"))
        self.verticalLayout.addWidget(self.favorites)
        self.horizontalLayout_6 = QtGui.QWidget(self.sidebarPage1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.addFavoriteBtn = QtGui.QPushButton(self.horizontalLayout_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFavoriteBtn.sizePolicy().hasHeightForWidth())
        self.addFavoriteBtn.setSizePolicy(sizePolicy)
        self.addFavoriteBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.addFavoriteBtn.setFlat(False)
        self.addFavoriteBtn.setObjectName(_fromUtf8("addFavoriteBtn"))
        self.horizontalLayout_2.addWidget(self.addFavoriteBtn)
        self.removeFavoriteBtn = QtGui.QPushButton(self.horizontalLayout_6)
        self.removeFavoriteBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.removeFavoriteBtn.setObjectName(_fromUtf8("removeFavoriteBtn"))
        self.horizontalLayout_2.addWidget(self.removeFavoriteBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 6)
        self.verticalLayout.addWidget(self.horizontalLayout_6)
        self.sidebar.addWidget(self.sidebarPage1)
        self.sidebarPage2 = QtGui.QWidget()
        self.sidebarPage2.setObjectName(_fromUtf8("sidebarPage2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.sidebarPage2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tables = QtGui.QListWidget(self.sidebarPage2)
        self.tables.setAlternatingRowColors(False)
        self.tables.setTextElideMode(QtCore.Qt.ElideRight)
        self.tables.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tables.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tables.setMovement(QtGui.QListView.Static)
        self.tables.setViewMode(QtGui.QListView.ListMode)
        self.tables.setUniformItemSizes(False)
        self.tables.setWordWrap(False)
        self.tables.setSelectionRectVisible(False)
        self.tables.setObjectName(_fromUtf8("tables"))
        self.verticalLayout_2.addWidget(self.tables)
        self.horizontalLayout_8 = QtGui.QWidget(self.sidebarPage2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addTableBtn = QtGui.QPushButton(self.horizontalLayout_8)
        self.addTableBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.addTableBtn.setObjectName(_fromUtf8("addTableBtn"))
        self.horizontalLayout_3.addWidget(self.addTableBtn)
        self.removeTableBtn = QtGui.QPushButton(self.horizontalLayout_8)
        self.removeTableBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.removeTableBtn.setObjectName(_fromUtf8("removeTableBtn"))
        self.horizontalLayout_3.addWidget(self.removeTableBtn)
        self.editTableBtn = QtGui.QPushButton(self.horizontalLayout_8)
        self.editTableBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.editTableBtn.setObjectName(_fromUtf8("editTableBtn"))
        self.horizontalLayout_3.addWidget(self.editTableBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 5)
        self.verticalLayout_2.addWidget(self.horizontalLayout_8)
        self.sidebar.addWidget(self.sidebarPage2)
        self.verticalLayout_5.addWidget(self.sidebar)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QWidget(self.layoutWidget)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayout_7)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.structureBtn = QtGui.QToolButton(self.horizontalLayout_7)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/structure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.structureBtn.setIcon(icon)
        self.structureBtn.setCheckable(True)
        self.structureBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.structureBtn.setObjectName(_fromUtf8("structureBtn"))
        self.horizontalLayout.addWidget(self.structureBtn)
        self.contentBtn = QtGui.QToolButton(self.horizontalLayout_7)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/data.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contentBtn.setIcon(icon1)
        self.contentBtn.setCheckable(True)
        self.contentBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.contentBtn.setObjectName(_fromUtf8("contentBtn"))
        self.horizontalLayout.addWidget(self.contentBtn)
        self.tableinfoBtn = QtGui.QToolButton(self.horizontalLayout_7)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/img/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tableinfoBtn.setIcon(icon2)
        self.tableinfoBtn.setCheckable(True)
        self.tableinfoBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tableinfoBtn.setObjectName(_fromUtf8("tableinfoBtn"))
        self.horizontalLayout.addWidget(self.tableinfoBtn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(3, 3)
        self.verticalLayout_7.addWidget(self.horizontalLayout_7)
        self.panel = QtGui.QStackedWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel.sizePolicy().hasHeightForWidth())
        self.panel.setSizePolicy(sizePolicy)
        self.panel.setLineWidth(1)
        self.panel.setObjectName(_fromUtf8("panel"))
        self.stackedWidgetPage1 = QtGui.QWidget()
        self.stackedWidgetPage1.setObjectName(_fromUtf8("stackedWidgetPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.stackedWidgetPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 2, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.con_password = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_password.setEchoMode(QtGui.QLineEdit.Password)
        self.con_password.setObjectName(_fromUtf8("con_password"))
        self.gridLayout.addWidget(self.con_password, 4, 1, 1, 2)
        self.con_name = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_name.setObjectName(_fromUtf8("con_name"))
        self.gridLayout.addWidget(self.con_name, 1, 1, 1, 2)
        self.con_host = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_host.setObjectName(_fromUtf8("con_host"))
        self.gridLayout.addWidget(self.con_host, 2, 1, 1, 2)
        self.connectBtn = QtGui.QPushButton(self.stackedWidgetPage1)
        self.connectBtn.setCheckable(False)
        self.connectBtn.setChecked(False)
        self.connectBtn.setAutoDefault(False)
        self.connectBtn.setDefault(False)
        self.connectBtn.setFlat(False)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.gridLayout.addWidget(self.connectBtn, 7, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.con_database = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_database.setObjectName(_fromUtf8("con_database"))
        self.gridLayout.addWidget(self.con_database, 5, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.con_port = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_port.setObjectName(_fromUtf8("con_port"))
        self.gridLayout.addWidget(self.con_port, 6, 1, 1, 2)
        self.saveFavoriteBtn = QtGui.QPushButton(self.stackedWidgetPage1)
        self.saveFavoriteBtn.setCheckable(False)
        self.saveFavoriteBtn.setObjectName(_fromUtf8("saveFavoriteBtn"))
        self.gridLayout.addWidget(self.saveFavoriteBtn, 7, 1, 1, 1)
        self.con_username = QtGui.QLineEdit(self.stackedWidgetPage1)
        self.con_username.setObjectName(_fromUtf8("con_username"))
        self.gridLayout.addWidget(self.con_username, 3, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.stackedWidgetPage1)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.stackedWidgetPage1)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 3)
        self.panel.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtGui.QWidget()
        self.stackedWidgetPage2.setObjectName(_fromUtf8("stackedWidgetPage2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.stackedWidgetPage2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.structure = QtGui.QTableWidget(self.stackedWidgetPage2)
        self.structure.setAlternatingRowColors(True)
        self.structure.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.structure.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.structure.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.structure.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.structure.setShowGrid(False)
        self.structure.setGridStyle(QtCore.Qt.NoPen)
        self.structure.setObjectName(_fromUtf8("structure"))
        self.structure.setColumnCount(8)
        self.structure.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.structure.setHorizontalHeaderItem(7, item)
        self.structure.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.structure)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addFieldBtn = QtGui.QPushButton(self.stackedWidgetPage2)
        self.addFieldBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.addFieldBtn.setObjectName(_fromUtf8("addFieldBtn"))
        self.horizontalLayout_4.addWidget(self.addFieldBtn)
        self.removeFieldBtn = QtGui.QPushButton(self.stackedWidgetPage2)
        self.removeFieldBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.removeFieldBtn.setObjectName(_fromUtf8("removeFieldBtn"))
        self.horizontalLayout_4.addWidget(self.removeFieldBtn)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.panel.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtGui.QWidget()
        self.stackedWidgetPage3.setObjectName(_fromUtf8("stackedWidgetPage3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.stackedWidgetPage3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.content = QtGui.QTableWidget(self.stackedWidgetPage3)
        self.content.setAlternatingRowColors(True)
        self.content.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.content.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.content.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.content.setShowGrid(False)
        self.content.setObjectName(_fromUtf8("content"))
        self.content.setColumnCount(0)
        self.content.setRowCount(0)
        self.content.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.content)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.addRowBtn = QtGui.QPushButton(self.stackedWidgetPage3)
        self.addRowBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.addRowBtn.setObjectName(_fromUtf8("addRowBtn"))
        self.horizontalLayout_5.addWidget(self.addRowBtn)
        self.removeRowBtn = QtGui.QPushButton(self.stackedWidgetPage3)
        self.removeRowBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.removeRowBtn.setObjectName(_fromUtf8("removeRowBtn"))
        self.horizontalLayout_5.addWidget(self.removeRowBtn)
        self.validateRowBtn = QtGui.QPushButton(self.stackedWidgetPage3)
        self.validateRowBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.validateRowBtn.setObjectName(_fromUtf8("validateRowBtn"))
        self.horizontalLayout_5.addWidget(self.validateRowBtn)
        self.cancelRowBtn = QtGui.QPushButton(self.stackedWidgetPage3)
        self.cancelRowBtn.setMinimumSize(QtCore.QSize(30, 0))
        self.cancelRowBtn.setObjectName(_fromUtf8("cancelRowBtn"))
        self.horizontalLayout_5.addWidget(self.cancelRowBtn)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.panel.addWidget(self.stackedWidgetPage3)
        self.stackedWidgetPage4 = QtGui.QWidget()
        self.stackedWidgetPage4.setObjectName(_fromUtf8("stackedWidgetPage4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.stackedWidgetPage4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.size_label = QtGui.QLabel(self.stackedWidgetPage4)
        self.size_label.setText(_fromUtf8(""))
        self.size_label.setObjectName(_fromUtf8("size_label"))
        self.gridLayout_3.addWidget(self.size_label, 3, 1, 1, 1)
        self.engine_label = QtGui.QLabel(self.stackedWidgetPage4)
        self.engine_label.setText(_fromUtf8(""))
        self.engine_label.setObjectName(_fromUtf8("engine_label"))
        self.gridLayout_3.addWidget(self.engine_label, 1, 1, 1, 1)
        self.created_label = QtGui.QLabel(self.stackedWidgetPage4)
        self.created_label.setText(_fromUtf8(""))
        self.created_label.setObjectName(_fromUtf8("created_label"))
        self.gridLayout_3.addWidget(self.created_label, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.encoding_label = QtGui.QLabel(self.stackedWidgetPage4)
        self.encoding_label.setText(_fromUtf8(""))
        self.encoding_label.setObjectName(_fromUtf8("encoding_label"))
        self.gridLayout_3.addWidget(self.encoding_label, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.rows_label = QtGui.QLabel(self.stackedWidgetPage4)
        self.rows_label.setText(_fromUtf8(""))
        self.rows_label.setObjectName(_fromUtf8("rows_label"))
        self.gridLayout_3.addWidget(self.rows_label, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.stackedWidgetPage4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 2, 1, 1, 1)
        self.panel.addWidget(self.stackedWidgetPage4)
        self.verticalLayout_7.addWidget(self.panel)
        self.verticalLayout_8.addWidget(self.splitter)
        self.log_viewer = QtGui.QPlainTextEdit(self.centralwidget)
        self.log_viewer.setBackgroundVisible(False)
        self.log_viewer.setObjectName(_fromUtf8("log_viewer"))
        self.verticalLayout_8.addWidget(self.log_viewer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.sidebar.setCurrentIndex(0)
        self.panel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PySequel", None))
        self.databases.setItemText(0, _translate("MainWindow", "Choose Database...", None))
        self.addFavoriteBtn.setText(_translate("MainWindow", "+", None))
        self.removeFavoriteBtn.setText(_translate("MainWindow", "-", None))
        self.addTableBtn.setText(_translate("MainWindow", "+", None))
        self.removeTableBtn.setText(_translate("MainWindow", "-", None))
        self.editTableBtn.setText(_translate("MainWindow", "Edit", None))
        self.structureBtn.setText(_translate("MainWindow", "Structure", None))
        self.contentBtn.setText(_translate("MainWindow", "Content", None))
        self.tableinfoBtn.setText(_translate("MainWindow", "Table Info", None))
        self.connectBtn.setText(_translate("MainWindow", "Connect", None))
        self.label_3.setText(_translate("MainWindow", "Username: ", None))
        self.con_database.setPlaceholderText(_translate("MainWindow", "Optional", None))
        self.label_6.setText(_translate("MainWindow", "Port: ", None))
        self.con_port.setPlaceholderText(_translate("MainWindow", "3306", None))
        self.saveFavoriteBtn.setText(_translate("MainWindow", "Save", None))
        self.label_4.setText(_translate("MainWindow", "Password: ", None))
        self.label.setText(_translate("MainWindow", "Name: ", None))
        self.label_5.setText(_translate("MainWindow", "Database: ", None))
        self.label_2.setText(_translate("MainWindow", "MySql Host: ", None))
        self.label_7.setText(_translate("MainWindow", "<strong>Enter connection details below, or choose a favorite</strong>", None))
        item = self.structure.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Field", None))
        item = self.structure.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.structure.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Length", None))
        item = self.structure.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Unsigned", None))
        item = self.structure.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nullable", None))
        item = self.structure.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Key", None))
        item = self.structure.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Default", None))
        item = self.structure.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Extra", None))
        self.addFieldBtn.setText(_translate("MainWindow", "+", None))
        self.removeFieldBtn.setText(_translate("MainWindow", "-", None))
        self.addRowBtn.setText(_translate("MainWindow", "+", None))
        self.removeRowBtn.setText(_translate("MainWindow", "-", None))
        self.validateRowBtn.setText(_translate("MainWindow", "☑", None))
        self.cancelRowBtn.setText(_translate("MainWindow", "☒", None))
        self.label_10.setText(_translate("MainWindow", "Engine:", None))
        self.label_12.setText(_translate("MainWindow", "Rows:", None))
        self.label_13.setText(_translate("MainWindow", "Size:", None))
        self.label_14.setText(_translate("MainWindow", "Encoding:", None))
        self.label_8.setText(_translate("MainWindow", "Created:", None))

import img_rc
